/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as DividendinvestingImport } from './routes/dividendinvesting'
import { Route as DdmcalcImport } from './routes/ddmcalc'
import { Route as DdmHistoryImport } from './routes/ddm-history'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const DividendinvestingRoute = DividendinvestingImport.update({
  id: '/dividendinvesting',
  path: '/dividendinvesting',
  getParentRoute: () => rootRoute,
} as any)

const DdmcalcRoute = DdmcalcImport.update({
  id: '/ddmcalc',
  path: '/ddmcalc',
  getParentRoute: () => rootRoute,
} as any)

const DdmHistoryRoute = DdmHistoryImport.update({
  id: '/ddm-history',
  path: '/ddm-history',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/ddm-history': {
      id: '/ddm-history'
      path: '/ddm-history'
      fullPath: '/ddm-history'
      preLoaderRoute: typeof DdmHistoryImport
      parentRoute: typeof rootRoute
    }
    '/ddmcalc': {
      id: '/ddmcalc'
      path: '/ddmcalc'
      fullPath: '/ddmcalc'
      preLoaderRoute: typeof DdmcalcImport
      parentRoute: typeof rootRoute
    }
    '/dividendinvesting': {
      id: '/dividendinvesting'
      path: '/dividendinvesting'
      fullPath: '/dividendinvesting'
      preLoaderRoute: typeof DividendinvestingImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ddm-history': typeof DdmHistoryRoute
  '/ddmcalc': typeof DdmcalcRoute
  '/dividendinvesting': typeof DividendinvestingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ddm-history': typeof DdmHistoryRoute
  '/ddmcalc': typeof DdmcalcRoute
  '/dividendinvesting': typeof DividendinvestingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ddm-history': typeof DdmHistoryRoute
  '/ddmcalc': typeof DdmcalcRoute
  '/dividendinvesting': typeof DividendinvestingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ddm-history'
    | '/ddmcalc'
    | '/dividendinvesting'
    | '/sign-in'
    | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ddm-history'
    | '/ddmcalc'
    | '/dividendinvesting'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ddm-history'
    | '/ddmcalc'
    | '/dividendinvesting'
    | '/sign-in'
    | '/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DdmHistoryRoute: typeof DdmHistoryRoute
  DdmcalcRoute: typeof DdmcalcRoute
  DividendinvestingRoute: typeof DividendinvestingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DdmHistoryRoute: DdmHistoryRoute,
  DdmcalcRoute: DdmcalcRoute,
  DividendinvestingRoute: DividendinvestingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/ddm-history",
        "/ddmcalc",
        "/dividendinvesting",
        "/sign-in",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/ddm-history": {
      "filePath": "ddm-history.tsx"
    },
    "/ddmcalc": {
      "filePath": "ddmcalc.tsx"
    },
    "/dividendinvesting": {
      "filePath": "dividendinvesting.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
