/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as DividendinvestingImport } from './routes/dividendinvesting'
import { Route as DdmHistoryImport } from './routes/ddm-history'
import { Route as CalculatorsImport } from './routes/calculators'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as CalculatorsDdmImport } from './routes/calculators/ddm'
import { Route as CalculatorsCompoundInterestImport } from './routes/calculators/compound-interest'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const DividendinvestingRoute = DividendinvestingImport.update({
  id: '/dividendinvesting',
  path: '/dividendinvesting',
  getParentRoute: () => rootRoute,
} as any)

const DdmHistoryRoute = DdmHistoryImport.update({
  id: '/ddm-history',
  path: '/ddm-history',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsRoute = CalculatorsImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CalculatorsDdmRoute = CalculatorsDdmImport.update({
  id: '/ddm',
  path: '/ddm',
  getParentRoute: () => CalculatorsRoute,
} as any)

const CalculatorsCompoundInterestRoute =
  CalculatorsCompoundInterestImport.update({
    id: '/compound-interest',
    path: '/compound-interest',
    getParentRoute: () => CalculatorsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsImport
      parentRoute: typeof rootRoute
    }
    '/ddm-history': {
      id: '/ddm-history'
      path: '/ddm-history'
      fullPath: '/ddm-history'
      preLoaderRoute: typeof DdmHistoryImport
      parentRoute: typeof rootRoute
    }
    '/dividendinvesting': {
      id: '/dividendinvesting'
      path: '/dividendinvesting'
      fullPath: '/dividendinvesting'
      preLoaderRoute: typeof DividendinvestingImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/calculators/compound-interest': {
      id: '/calculators/compound-interest'
      path: '/compound-interest'
      fullPath: '/calculators/compound-interest'
      preLoaderRoute: typeof CalculatorsCompoundInterestImport
      parentRoute: typeof CalculatorsImport
    }
    '/calculators/ddm': {
      id: '/calculators/ddm'
      path: '/ddm'
      fullPath: '/calculators/ddm'
      preLoaderRoute: typeof CalculatorsDdmImport
      parentRoute: typeof CalculatorsImport
    }
  }
}

// Create and export the route tree

interface CalculatorsRouteChildren {
  CalculatorsCompoundInterestRoute: typeof CalculatorsCompoundInterestRoute
  CalculatorsDdmRoute: typeof CalculatorsDdmRoute
}

const CalculatorsRouteChildren: CalculatorsRouteChildren = {
  CalculatorsCompoundInterestRoute: CalculatorsCompoundInterestRoute,
  CalculatorsDdmRoute: CalculatorsDdmRoute,
}

const CalculatorsRouteWithChildren = CalculatorsRoute._addFileChildren(
  CalculatorsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/ddm-history': typeof DdmHistoryRoute
  '/dividendinvesting': typeof DividendinvestingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calculators/compound-interest': typeof CalculatorsCompoundInterestRoute
  '/calculators/ddm': typeof CalculatorsDdmRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/ddm-history': typeof DdmHistoryRoute
  '/dividendinvesting': typeof DividendinvestingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calculators/compound-interest': typeof CalculatorsCompoundInterestRoute
  '/calculators/ddm': typeof CalculatorsDdmRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRouteWithChildren
  '/ddm-history': typeof DdmHistoryRoute
  '/dividendinvesting': typeof DividendinvestingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/calculators/compound-interest': typeof CalculatorsCompoundInterestRoute
  '/calculators/ddm': typeof CalculatorsDdmRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators'
    | '/ddm-history'
    | '/dividendinvesting'
    | '/sign-in'
    | '/sign-up'
    | '/calculators/compound-interest'
    | '/calculators/ddm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators'
    | '/ddm-history'
    | '/dividendinvesting'
    | '/sign-in'
    | '/sign-up'
    | '/calculators/compound-interest'
    | '/calculators/ddm'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators'
    | '/ddm-history'
    | '/dividendinvesting'
    | '/sign-in'
    | '/sign-up'
    | '/calculators/compound-interest'
    | '/calculators/ddm'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorsRoute: typeof CalculatorsRouteWithChildren
  DdmHistoryRoute: typeof DdmHistoryRoute
  DividendinvestingRoute: typeof DividendinvestingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorsRoute: CalculatorsRouteWithChildren,
  DdmHistoryRoute: DdmHistoryRoute,
  DividendinvestingRoute: DividendinvestingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/calculators",
        "/ddm-history",
        "/dividendinvesting",
        "/sign-in",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/calculators": {
      "filePath": "calculators.tsx",
      "children": [
        "/calculators/compound-interest",
        "/calculators/ddm"
      ]
    },
    "/ddm-history": {
      "filePath": "ddm-history.tsx"
    },
    "/dividendinvesting": {
      "filePath": "dividendinvesting.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/calculators/compound-interest": {
      "filePath": "calculators/compound-interest.tsx",
      "parent": "/calculators"
    },
    "/calculators/ddm": {
      "filePath": "calculators/ddm.tsx",
      "parent": "/calculators"
    }
  }
}
ROUTE_MANIFEST_END */
